# Generated by Django 3.2.8 on 2022-01-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='judul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='pemilih',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namapemilih', models.TextField(default='')),
                ('nikpemilih', models.IntegerField(unique=True)),
                ('tempatpemilih', models.TextField(default='')),
                ('nomerpemilih', models.IntegerField(default='13')),
                ('emailpemilih', models.EmailField(max_length=224)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='tambahadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namapanitia', models.TextField(default='')),
                ('username', models.TextField(default='')),
                ('emailpanitia', models.EmailField(max_length=224)),
                ('password', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='tambahkandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namakandidat', models.TextField(default='', max_length=100)),
                ('nomerurut', models.IntegerField(default='')),
                ('tempatlahir', models.TextField(default='', max_length=100)),
                ('tanggallahir', models.CharField(max_length=200)),
                ('alamat', models.TextField(default='', max_length=100)),
                ('pengalaman', models.TextField(default='', max_length=100)),
                ('prestasi', models.TextField(default='', max_length=100)),
                ('visi', models.TextField(default='', max_length=100)),
                ('misi', models.TextField(default='', max_length=100)),
                ('programkerja', models.TextField(default='', max_length=100)),
                ('kandidat_Main_Img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
